# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(max_length=500, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=1000, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='email_from',
            field=models.EmailField(blank=True, help_text='The address the email will be sent from', max_length=254, verbose_name='From address'),
        ),
    ]
